<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "np_lexikon"
 *
 * Auto generated by Extension Builder 2014-02-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cacheable Extbase Controller Actions',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Martin Tillmann',
	'author_email' => 'tillmann@network-publishing.de',
	'author_company' => 'network.publishing GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
